---
title: "ZCB Pricing"
author:
- Valentine Chisango
- George Parekkadavil
- Vegan Pather
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls(all =TRUE))
```

```{r 1}
# Closed form solution of the Bond price

bond_price <- function(alpha=0.08,beta=0.8,sigma=0.005,t=0,T=5,r=0.08){
  # alpha, beta, sigma <- Fixed Parameters
  # T <- maturity time
  # r <- Initial rate at time 0  
  A <- (1-exp(-beta*(T-t)))/(beta)
  B <- (1/beta)*((alpha-(sigma)^2/(2*beta))*(A - T +t) - (sigma^(2)*A^2)/(4))
  exp(-A*r +B)
}

```

```{r 2}

# Crude Monte Carlo function 

Crude_Monte_Carlo=function(alpha =0.08,beta=0.8,sigma=0.005,T=5,r = 0.08,n=10000,s=1250){
  
  # alpha, beta, sigma <- Fixed Parameters
  # T <- maturity time
  # r <- Initial rate at time 0
  # n <- Number of Simulations
  # s <- NUmber of Sub-intervals over time 
  
  #Simulate interest rates
  dt <- T/s # Length of sub-intervals
  sim_path = matrix(0,s+1,n) # Matrix that stores rate pathways
  sim_path[1,]= r # Initial rates on first row.
  
  z = matrix(nrow=n, ncol=s) # Create a matrix of standardised normal random variables
  for (i in 1:n){
    z[i,]=rnorm(s)
  }
  
  for (i in 1:n){
    for (j in 2:(s+1)){
      dr=(alpha-beta*sim_path[j-1,i])*dt+sigma*sqrt(dt)*z[i,j-1]# Discretize the SDE of the interest model using the Euler Discretization to simulate rates over discrete sub-intervals
      sim_path[j,i]=sim_path[j-1,i]+dr
    }
  }
  
  # Monte Carlo Simulations
  Sum = colSums(sim_path[2:(s+1),]*dt) # Approximate the integral using summation
  int = exp(-Sum) # Take the exponent of the Integral
  mean = mean(int) # Find the average of expressions
  mean
  
}


```

```{r 3}
# Improvements to the Monte Carlo Simulation

# Antithetic Variates

Antithetic_variates = function(alpha =0.08,beta=0.8,sigma=0.005,T=5,r = 0.08,n=10000,s=1250){

  # alpha, beta, sigma <- Fixed Parameters
  # T <- maturity time
  # r <- Initial rate at time 0
  # n <- Number of Simulations
  # s <- NUmber of Sub-intervals over time   
  
  dt <- T/s # Length of sub-intervals
  sim_path= matrix(0,s+1,n) # Matrix that stores rate pathways
  sim_path_inv= matrix(0,nrow = s+1, ncol = n)# matrix to generate interest paths using negative values of RV
  sim_path[1,] = r # Inital rates on first row
  sim_path_inv[1,] = r
 
   z = matrix(nrow=n, ncol=s) # Create a matrix of standardised normal random variables
  for (i in 1:n){
    z[i,]=rnorm(s)
  }
  z.=-z #Take the negative of above matrix
  
  
  for (i in 1:n){
    for (j in 2:(s+1)){
      dr = (alpha-beta*sim_path[j-1,i])*dt+sigma*sqrt(dt)*z[i,j-1] # Same Euler Discretization as in the Crude Monte Carlo function
      dr_i = (alpha-beta*sim_path_inv[j-1,i])*dt + sigma*sqrt(dt)*z.[i,j-1] # Euler Discretization for the use of -Z_i
      sim_path[j,i] =sim_path[j-1,i]+dr
      sim_path_inv[j,i] = sim_path_inv[j-1,i]+dr_i
      
    }
  }
  
  # Monte Carlo Simulations
  Sum = colSums(sim_path[2:(s+1),]*dt) # The Sum and Sum. variables record the summation of their respective rates to approximate the integral
  Sum.= colSums(sim_path_inv[2:(s+1),]*dt)
  int = exp(-Sum.) #Exponential of the estimate using Z_i
  int.= exp(-Sum) #Exponential of the estimate using -Z_i
  mean_1 = mean(int) # Estimate using Z_i
  mean_2 = mean(int.)  # Estimate using -Z_i
  result = (mean_1+mean_2)/2 # Final estimate is taken as the average of the two estimates.
  result
  
}


```

```{r 4}

# Moment matching

Moment_Matching = function(alpha = 0.08, beta = 0.8, sigma = 0.005, T = 5,r = 0.08, n = 10000, s = 1250){
  
  # alpha, beta, sigma <- Fixed Parameters
  # T <- maturity time
  # r0 <- Initial rate at time 0
  # n <- Number of Simulations
  # s <- NUmber of Subintervals 
  
  #Simulate interest rates
  dt <- T/s # Length of sub-intervals
  sim_path= matrix(0,s+1,n) # Matrix that stores rate pathways
  sim_path[1,]= r
  z = matrix(nrow=n, ncol=s)
  for (i in 1:n){
    z[i,]=rnorm(s) # Create a matrix of standardised normal random variables
  }
  
  z_m = matrix(nrow=n, ncol=s)
  for (i in 1:n){
    z_m[i,]=z[i,]-mean(z[i,]) # Perform the moment matching transformation on the                                 above generated random variables
  }
  # Moment matching transformation of Z_i to match finite moments 
  
  # Follow the same process as in the Monte Carlo approach , but use the transformed Z_i's to simulate the rates
  for (i in 1:n){
    for (j in 2:(s+1)){
      dr=(alpha-beta*sim_path[j-1,i])*dt+sigma*sqrt(dt)*z_m[i,j-1] 
      sim_path[j,i]=sim_path[j-1,i]+dr
    }
  }
  
  Sum=colSums(sim_path[2:(s+1),]*dt)
  int=exp(-Sum)  # Take the exponent of the Integral
  result=mean(int) # Find the average of expression
  result

}

```

```{r 5}

# Control Variates

# Make use of the Cox Ingeresoll Ross (CIR) model as the control variate process.
# Below is the closed form solution of a ZCB under the CIR model
bond_price_CIR <- function(alpha =0.08,beta=0.8,sigma=0.005,t=0,T=5,r = 0.08){
  h <- sqrt(beta^(2)+2*sigma^(2))
  A <-(2*h*exp((beta+h)*(T-t)/2)/(2*h+(beta+h)*(exp((T-t)*(h))-1)))^((2*alpha)/sigma^(2))
  B <-2*(exp((T-t)*(h))-1)/(2*h+(beta+h)*(exp((T-t)*(h))-1))
  A*exp(-B*r)
}


# Monte Carlo Simulations of Bond Price under the CIR model

CIR_MC= function(alpha =0.08,beta=0.8,sigma=0.005,T=5,r = 0.08,n=10000,s=1250){
  
  dt <- T/s # Length of sub-intervals
  sim_path= matrix(0,s+1,n) # Matrix that stores rate pathways
  sim_path[1,]= r
  z = matrix(nrow=n, ncol=s)
  for (i in 1:n){
    z[i,]=rnorm(s) # Create a matrix of standardised normal random variables
  }
  
  for (i in 1:n){
    for (j in 2:(s+1)){
      dr=(alpha-beta*sim_path[j-1,i])*dt+(sigma*sqrt(dt)*z[i,j-1]*sqrt(sim_path[j-1,i]))# Euler Discretization
      sim_path[j,i]=sim_path[j-1,i]+dr
    
    }
  }
  
  # Monte Carlo Simulations
  Sum=colSums(sim_path[2:(s+1),]*dt)
  int=exp(-Sum)
  result=mean(int)
  result
  
}
# The Control Variate estimate is taken as the difference between the the Crude Monte Carlo estimates of the Vasicek and CIR model plus the closed form solution of the CIR model

Control_Variates_estimate= function(alpha =0.08,beta=0.8,sigma=0.005,t=0,T=5,r = 0.08,n=10000,s=1250){
  Crude_Monte_Carlo(alpha,beta,sigma,T,r,n,s)- CIR_MC(alpha,beta,sigma,T,r,n,s)+bond_price_CIR(alpha,beta,sigma,t,T,r)
}



```

```{r 6}
# Explicit Method

explicit = function(alpha = 0.08,beta = 0.8, sigma = 0.005,r = 0.08, I = 1:1250, J = seq(-0.4,0.6,0.005),T = 5){
  
  # I = partition of time interval
  # J = partition of short rates sequence
  
  M <- length(J) # Number of short rate grid points
  N <- length(I) # Number of time grid poiints
  
  
  dt <- T/N # Lenght of each time subinterval
  dr <- J[2] -J[1] # Lenght of each time interval
  
  # For each j in J we define the following functions at a fixed time point
  
  pd <- function(j){
    ((J[j]+1/dt)^(-1))*(sigma^2/(2*(dr^2)) -(alpha -beta*J[j])/(2*dr))
  }
  
  
  pm <- function(j){
    ((J[j]+1/dt)^(-1))*(1/dt -sigma^2/(dr^2))
  }
  
  
  pu <- function(j){
    ((J[j]+1/dt)^(-1))*(sigma^2/(2*(dr^2)) + (alpha -beta*J[j])/(2*dr))
  }

  #Setting up tridiagonal matrix
  
  Diag_1 <- matrix(0,ncol = M, nrow = M)
  
  # Filling main diagonal of matrix 
  for (j in 1:M){
    Diag_1[j,j] <- pm(j)
    
  }
  
  # Filling lower diagonal of matrix 
  for (j in 2:M){
    Diag_1[j,j-1] <- pd(j)
  }
  
  # Filling upper diagonal of matirx 
  for (j in 1:(M-1)){
    Diag_1[j,j+1] <- pu(j)
  }  
  
  # Bond price values at maturity are all 1 unit   
  Bond_values <- matrix(1,nrow=M, ncol =1)
  
  # Working backwards in time
  for (i in 1:(length(I))){
    C <- matrix(0,ncol = 1, nrow = M) # Another matrix for boundary conditions
    C[M,1] <- (pu(M))*Bond_values[M,1]
    C[1,1] <- pd(1)*Bond_values[1,1]
    
    Bond_values <- Diag_1%*%Bond_values# New values of bond prices based on next time price
    Bond_values <- Bond_values
  }
  
  # Finding index of the desired short rate
  index = match(as.character(r),J)
  # Output is the corresponding bond price at time 0
  Bond_values[index]
}



```

```{r 7}
# Implicit Method


implicit <- function(alpha = 0.08,beta = 0.8,sigma = 0.005,r = 0.08,I = 1:1250, J =seq(-0.4,0.6,0.005),T=5){
  
  # I = partition of time interval
  # J = partition of short rate variable
  
  M <- length(J) # Number of short rate grid points
  N <- length(I) # Number of time grid poiint
  
  dr <- J[2] - J[1] # length of each sub-interval across J
  dt <- T/N # length of each sub-interval across I
  
  # For each j in J we define the following functions at a fixed time point
  
  pd <- function(j){
    dt*((alpha-beta*J[j])/(2*dr) - (sigma^2)/(2*dr^2))
    
  }
  
  pm <- function(j){
    dt*(J[j] + 1/dt +sigma^2/(dr^2))
  }
  
  pu <- function(j){
    -dt*((alpha-beta*J[j])/(2*dr) + (sigma^2)/(2*dr^2))
  }
  
  # Setting up tridiagonal matrix
  Diag <- matrix(0,nrow = M,ncol = M)
  
  # Filling main diagonal
  for (j in 1:M){
    Diag[j,j] <- pm(j)
    
  }
  
  # Filling lower diagonal
  for (j in 2:M){
    Diag[j,j-1] <- pd(j)
  }
  
  # Filling upper diagonal
  for (j in 1:(M-1)){
    Diag[j,j+1] <- pu(j)
  }
  
  
  Bond_values <- matrix(1,ncol = 1,nrow = M) # The matrix of bond prices at maturity time 
  Inv <- solve(Diag) # Inverse of tridiagonal matrix
  
  for (i in 1:(length(I))){
    C <- matrix(0,ncol = 1, nrow = M) # Another matrix for boundary conditions
    C[M,1] <- (-pu(M))*Bond_values[M,1]
    C[1,1] <- -pd(1)*Bond_values[1,1]

    RHS <- Bond_values + C # Working backwards recursively 
    Bond_values <- Inv%*%RHS
  }

  # Finding index of the desired short rate
  index = match(as.character(r),J)
  # Output is the corresponding bond price at time 0
  Bond_values[index]
}

```

```{r 8}
# Crank-Nicholson Method


CN <- function(alpha = 0.08, beta = 0.8, sigma = 0.005, r = 0.08, T = 5 , I = 1:1250, J = seq(-0.4,0.6,0.005)){
  
  # I = partition of time interval
  # J = partition of short rate interval
  
  M <- length(J) # Number of short rate grid points
  N <- length(I) # Number of time grid poiints
  
  dt <- T/N # Length of each time subinterval
  dr <- J[2] -J[1] # Lenght of each rate subinterval
  
  #========================================================================================
  # Define the following functions for j = 1,...,M at each time point i
  
  pd <- function(j){
    (alpha -beta*J[j])/(4*dr) - sigma^2/(4*(dr^2))
  }
  
  pm <- function(j){
    sigma^2/(2*(dr^2)) + J[j]/2
  }
  
  pu <- function(j){
    -(alpha -beta*J[j])/(4*dr) - sigma^2/(4*(dr^2)) 
  }
  
  #========================================================================================
  # Define 2 tridiagonal matricies. One for time point i and one for time point i+1
  
  Diag_1 <- matrix(0,nrow = M,ncol = M)
  Diag_2 <- matrix(0,nrow = M,ncol = M)
  
  # Filling main diagonal of matrix 1
  for (j in 1:M){
    Diag_1[j,j] <- -1/dt - pm(j)
  }
  
  # Filling lower diagonal of matrix 1
  for (j in 2:M){
    Diag_1[j,j-1] <- -pd(j)
  }
  
  # Filling upper diagonal of matirx 1
  for (j in 1:M-1){
    Diag_1[j,j+1] <- -pu(j)
  }  
  
  
  # Filling main diagonal of matrix 2
  for (j in 1:M){
    Diag_2[j,j] <- -1/dt + pm(j)
    }
  
  # Filling lower diagonal of matrix 2
  for (j in 2:M){
    Diag_2[j,j-1] <- pd(j)
    }
  
  # Filling upper diagonal of matirx 2
  for (j in 1:M-1){
    Diag_2[j,j+1] <- pu(j)
  }
  
  
  #========================================================================================
  # Constructing more matricies and iterating the procedure from maturity to time 0
  Inv <- solve(Diag_1) # Inverse of 1st tridiagonal matrix
  
  # These 2 matricies are used for the recursive algorithm
  Bond_values_1 <- matrix(1,nrow = M, ncol = 1) 
  Bond_values_2 <- matrix(1,nrow = M, ncol = 1)
  
  # Calculation for first time step backwards
  C_1 <- matrix(0,nrow = M,ncol = 1)
  C_1[1,1] <- pd(1)*Bond_values_1[1,1] # Matrix for boundary conditions
  C_1[M,1] <- pu(M)*Bond_values_1[M,1]
  RHS <- Diag_2%*%Bond_values_1 +2*C_1
  Bond_values_1 <- Inv%*%RHS  
 

  for (i in 1:(length(I)-1)){
    C_2 <- matrix(0,nrow = M,ncol = 1)
    C_2[1,1] <- pd(1)*Bond_values_2[1,1]
    C_2[M,1] <- pu(M)*Bond_values_2[M,1]
  
    C_1 <- matrix(0,nrow = M,ncol = 1)
    C_1[1,1] <- pd(1)*Bond_values_1[1,1]
    C_1[M,1] <- pu(M)*Bond_values_1[M,1]
    
    RHS <- Diag_2%*%Bond_values_1 + C_1 + C_2
    Bond_values <- Inv%*%RHS
    Bond_values_2 <- Bond_values_1 # One of the matricies depends on current time
    Bond_values_1 <- Bond_values # One of the matricies depends on next time step
  }

  # Index of rate corresponding to desired short rate
  index = match(as.character(r), J)
  # Output corresponding to desired short rate
  Bond_values[index]
}

```

```{r 9}
# Comparison of results for numerical methods


compare_mat <- matrix(NA,nrow = 7, ncol = 4) # matrix of comparison

colnames(compare_mat) <- c("Price", "Known Price", "Error", "System Time")
rownames(compare_mat) <- c("Crude Monte Carlo", "Antithetic Variates", "Moment Matching", "Control Variates", "Explicit Method", "Implicit Method", "Crank-Nicolson Method")

compare_mat[,2] <- bond_price() # Known solution bond price

# Crude Monte Carlo
start_time <- proc.time()[1] # System time before method starts
compare_mat[1,1] <- Crude_Monte_Carlo()
compare_mat[1,4] <- proc.time()[1] - start_time # Getting difference of times
compare_mat[1,3] <- compare_mat[1,2] - compare_mat[1,1]

# Antithetic Variates
start_time <- proc.time()[1]
compare_mat[2,1] <- Antithetic_variates()
compare_mat[2,4] <- proc.time()[1] - start_time
compare_mat[2,3] <- compare_mat[2,2] - compare_mat[2,1]

# Moment Matching
start_time <- proc.time()[1]
compare_mat[3,1] <- Moment_Matching()
compare_mat[3,4] <- proc.time()[1] - start_time
compare_mat[3,3] <- compare_mat[3,2] - compare_mat[3,1]

# Control Variates
start_time <- proc.time()[1]
compare_mat[4,1] <- Control_Variates_estimate()
compare_mat[4,4] <- proc.time()[1] - start_time
compare_mat[4,3] <- compare_mat[4,2] - compare_mat[4,1]

# Explicit method
start_time <- proc.time()[1]
compare_mat[5,1] <- explicit()
compare_mat[5,4] <- proc.time()[1] - start_time
compare_mat[5,3] <- compare_mat[5,2] - compare_mat[5,1]

# Implicit method
start_time <- proc.time()[1]
compare_mat[6,1] <- implicit()
compare_mat[6,4] <- proc.time()[1] - start_time
compare_mat[6,3] <- compare_mat[6,2] - compare_mat[6,1]

# Crank-Nicolson method
start_time <- proc.time()[1]
compare_mat[7,1] <- CN()
compare_mat[7,4] <- proc.time()[1] - start_time
compare_mat[7,3] <- compare_mat[7,2] - compare_mat[7,1]

library(xtable) # package to get LaTex code for table
xtable(compare_mat, digits = 5) # Output of LaTex code for table
       
```

```{r 10}
# Sensitivity Tests

senses <- matrix(nrow=13, ncol=9) # matrix to hold prices for various parameters
colnames(senses) <-c("Parameters","Closed Form","Crude Monte Carlo","Antithetic Variates","Moment Matching","Control Variates","Explicit","Implicit","Crank-Nicholson")
xvec=c("Closed Form","Crude","AV","MM","CV","Explicit","Implicit","CN") #list of numerical methods

#Initial Parameters
senses[1,2]=bond_price()
senses[1,3]=Crude_Monte_Carlo()
senses[1,4]=Antithetic_variates()
senses[1,5]=Moment_Matching()
senses[1,6]=Control_Variates_estimate()
senses[1,7]=explicit()
senses[1,8]=implicit()
senses[1,9]=CN()

#Interest rate changes
#==============================================================================#
#r=0.05
senses[2,2]=bond_price(r=0.05)
senses[2,3]=Crude_Monte_Carlo(r=0.05)
senses[2,4]=Antithetic_variates(r=0.05)
senses[2,5]=Moment_Matching(r=0.05)
senses[2,6]=Control_Variates_estimate(r=0.05)
senses[2,7]=explicit(r=0.05)
senses[2,8]=implicit(r=0.05)
senses[2,9]=CN(r=0.05)

#r=0.1
senses[3,2]=bond_price(r=0.1)
senses[3,3]=Crude_Monte_Carlo(r=0.1)
senses[3,4]=Antithetic_variates(r=0.1)
senses[3,5]=Moment_Matching(r=0.1)
senses[3,6]=Control_Variates_estimate(r=0.1)
senses[3,7]=explicit(r=0.1)
senses[3,8]=implicit(r=0.1)
senses[3,9]=CN(r=0.1)

#Time to maturity changes
#==============================================================================#
#T=1
senses[4,2]=bond_price(T=1)
senses[4,3]=Crude_Monte_Carlo(T=1)
senses[4,4]=Antithetic_variates(T=1)
senses[4,5]=Moment_Matching(T=1)
senses[4,6]=Control_Variates_estimate(T=1)
senses[4,7]=explicit(T=1)
senses[4,8]=implicit(T=1)
senses[4,9]=CN(T=1)

#T=10
senses[5,2]=bond_price(T=10)
senses[5,3]=Crude_Monte_Carlo(T=10)
senses[5,4]=Antithetic_variates(T=10)
senses[5,5]=Moment_Matching(T=10)
senses[5,6]=Control_Variates_estimate(T=10)
senses[5,7]=explicit(T=10)
senses[5,8]=implicit(T=10)
senses[5,9]=CN(T=10)

#Changes to the sigma parameter
#===============================================================================#
#sigma=0.001
senses[6,2]=bond_price(sigma=0.001)
senses[6,3]=Crude_Monte_Carlo(sigma=0.001)
senses[6,4]=Antithetic_variates(sigma=0.001)
senses[6,5]=Moment_Matching(sigma=0.001)
senses[6,6]=Control_Variates_estimate(sigma=0.001)
senses[6,7]=explicit(sigma=0.001)
senses[6,8]=implicit(sigma=0.001)
senses[6,9]=CN(sigma=0.001)


#sigma=0.01
senses[7,2]=bond_price(sigma=0.01)
senses[7,3]=Crude_Monte_Carlo(sigma=0.01)
senses[7,4]=Antithetic_variates(sigma=0.01)
senses[7,5]=Moment_Matching(sigma=0.01)
senses[7,6]=Control_Variates_estimate(sigma=0.01)
senses[7,7]=explicit(sigma=0.01)
senses[7,8]=implicit(sigma=0.01)
senses[7,9]=CN(sigma=0.01)

#Changes to the alpha parameter
#===============================================================================#
#alpha=0.01
senses[8,2]=bond_price(alpha=0.01)
senses[8,3]=Crude_Monte_Carlo(alpha=0.01)
senses[8,4]=Antithetic_variates(alpha=0.01)
senses[8,5]=Moment_Matching(alpha=0.01)
senses[8,6]=Control_Variates_estimate(alpha=0.01)
senses[8,7]=explicit(alpha=0.01)
senses[8,8]=implicit(alpha=0.01)
senses[8,9]=CN(alpha=0.01)

#alpha=0.16
senses[9,2]=bond_price(alpha=0.16)
senses[9,3]=Crude_Monte_Carlo(alpha=0.16)
senses[9,4]=Antithetic_variates(alpha=0.16)
senses[9,5]=Moment_Matching(alpha=0.16)
senses[9,6]=Control_Variates_estimate(alpha=0.16)
senses[9,7]=explicit(alpha=0.16)
senses[9,8]=implicit(alpha=0.16)
senses[9,9]=CN(alpha=0.16)

#Changes to the beta value
#===============================================================================#
#beta=0.1
senses[10,2]=bond_price(beta=0.1)
senses[10,3]=Crude_Monte_Carlo(beta=0.1)
senses[10,4]=Antithetic_variates(beta=0.1)
senses[10,5]=Moment_Matching(beta=0.1)
senses[10,6]=Control_Variates_estimate(beta=0.1)
senses[10,7]=explicit(beta=0.1)
senses[10,8]=implicit(beta=0.1)
senses[10,9]=CN(beta=0.1)

#beta=1.6
senses[11,2]=bond_price(beta=1.6)
senses[11,3]=Crude_Monte_Carlo(beta=1.6)
senses[11,4]=Antithetic_variates(beta=1.6)
senses[11,5]=Moment_Matching(beta=1.6)
senses[11,6]=Control_Variates_estimate(beta=1.6)
senses[11,7]=explicit(beta=1.6)
senses[11,8]=implicit(beta=1.6)
senses[11,9]=CN(beta=1.6)

#Changes to the alpha and beta parameter
#===============================================================================#
#alpha=0.01,beta=0.1
senses[12,2]=bond_price(alpha=0.01,beta=0.1)
senses[12,3]=Crude_Monte_Carlo(alpha=0.01,beta=0.1)
senses[12,4]=Antithetic_variates(alpha=0.01,beta=0.1)
senses[12,5]=Moment_Matching(alpha=0.01,beta=0.1)
senses[12,6]=Control_Variates_estimate(alpha=0.01,beta=0.1)
senses[12,7]=explicit(alpha=0.01,beta=0.1)
senses[12,8]=implicit(alpha=0.01,beta=0.1)
senses[12,9]=CN(alpha=0.01,beta=0.1)

#alpha=0.16,beta=1.6
senses[13,2]=bond_price(alpha=0.16,beta=1.6)
senses[13,3]=Crude_Monte_Carlo(alpha=0.16,beta=1.6)
senses[13,4]=Antithetic_variates(alpha=0.16,beta=1.6)
senses[13,5]=Moment_Matching(alpha=0.16,beta=1.6)
senses[13,6]=Control_Variates_estimate(alpha=0.16,beta=1.6)
senses[13,7]=explicit(alpha=0.16,beta=1.6)
senses[13,8]=implicit(alpha=0.16,beta=1.6)
senses[13,9]=CN(alpha=0.16,beta=1.6)

# Labels for first column
senses[1,1]="-"
senses[2,1]="r=0.05"
senses[3,1]="r=0.1"
senses[4,1]="T=1"
senses[5,1]="T=10"
senses[6,1]="sigma=0.001"
senses[7,1]="sigma=0.01"
senses[8,1]="alpha=0.01"
senses[9,1]="alpha=0.16"
senses[10,1]="beta=0.1"
senses[11,1]="beta=1.6"
senses[12,1]="alpha=0.01,beta=0.1"
senses[13,1]="alpha=0.16,beta=1.6"

# Plots of sensitivity tests
par(mfrow=c(1,1))
plot(x=1:8,y=senses[1,2:9], ylim =c(0.58,0.66), xlab = "Numerical Method", ylab = "Bond Price", main = "Sensitivity Test: Interest Rate", xaxt = "n", col ="black", pch = 19, font.main = 1)
axis(1, at=1:8, labels=xvec)
lines(1:8, senses[2,2:9], col="red",type = "p", pch = 19)
lines(1:8, senses[3,2:9],col ="blue",type = "p", pch =19)
legend("bottomright", inset = c(-0,0), legend = c("r = 0.05", "r = 0.08", "r = 0.10"), lty = c(1,1,1), col = c("red","black","blue", "red"), cex = 0.8, bty ="n", pch =19)


plot(x=1:8,y=senses[1,2:9], ylim =c(-0.4,1.4), xlab = "Numerical Method", ylab = "Bond Price", main = "Sensitivity Test: Time to maturity", xaxt = "n", col ="black", pch = 19, font.main = 1)
axis(1, at=1:8, labels=xvec)
lines(1:8, senses[4,2:9], col="red",type = "p", pch = 19)
lines(1:8, senses[5,2:9],col ="blue",type = "p", pch = 19)
legend("bottomright", inset = c(-0,0), legend = c("T=1", "T=5", "T=10"), lty = c(1,1,1), col = c("red","black","blue", "red"), cex = 0.8, bty ="n", pch = 19)

plot(x=1:8,y=senses[1,2:9], ylim =c(0.58,0.66), xlab = "Numerical Method", ylab = "Bond Price", main = "Sensitivity Test: Sigma", xaxt = "n", col ="black", pch = 19, font.main = 1)
axis(1, at=1:8, labels=xvec)
lines(1:8, senses[6,2:9], col="red",type = "p", pch = 19)
lines(1:8, senses[7,2:9],col ="blue",type = "p", pch = 19)
legend("bottomright", inset = c(-0,0), legend = c("sigma=0.001", "sigma=0.005", "sigma=0.1"), lty = c(1,1,1), col = c("red","black","blue", "red"), cex = 0.8, bty ="n", pch = 19)

plot(x=1:8,y=senses[1,2:9], ylim =c(-0.4,1.4), xlab = "Numerical Method", ylab = "Bond Price", main = "Sensitivity Test: Alpha", xaxt = "n", col ="black", pch = 19, font.main = 1)
axis(1, at=1:8, labels=xvec)
lines(1:8, senses[8,2:9], col="red",type = "p",pch = 19)
lines(1:8, senses[9,2:9],col ="blue",type = "p",pch = 19)
legend("bottomright", inset = c(-0,0), legend = c("alpha=0.01", "alpha=0.08", "alpha=0.16"), lty = c(1,1,1), col = c("red","black","blue", "red"), cex = 0.8, bty ="n",pch = 19)

plot(x=1:8,y=senses[1,2:9], ylim =c(-0.4,1.4), xlab = "Numerical Method", ylab = "Bond Price", main = "Sensitivity Test: Beta", xaxt = "n", col ="black", pch = 19, font.main = 1)
axis(1, at=1:8, labels=xvec)
lines(1:8, senses[10,2:9], col="red",type = "p",pch = 19)
lines(1:8, senses[11,2:9],col ="blue",type = "p",pch = 19)
legend("bottomright", inset = c(-0,0), legend = c("beta=0.1", "beta=0.8", "beta=1.6"), lty = c(1,1,1), col = c("red","black","blue", "red"), cex = 0.8, bty ="n",pch = 19)

plot(x=1:8,y=senses[1,2:9], ylim =c(0.58,0.68), xlab = "Numerical Method", ylab = "Bond Price", main = "Sensitivity Test: Alpha & Beta",  xaxt = "n", col ="black", pch = 19, font.main = 1)
axis(1, at=1:8, labels=xvec)
lines(1:8, senses[12,2:9], col="red",type = "p",pch = 19)
lines(1:8, senses[13,2:9],col ="blue",type = "p",pch = 19)
legend("bottomright", inset = c(-0,0), legend = c("alpha=0.01,beta=0.1", "alpha=0.08,beta=0.8", "alpha=0.16,beta=1.6"), lty = c(1,1,1), col = c("red","black","blue", "red"), cex = 0.8, bty ="n",pch = 19)


senses[,2:9] <-round(as.numeric(senses[,2:9]), digits=5)
library(xtable) 
xtable(senses, digits = 5) # Table for data on sensitvity tests found in appendix B
```

```{r 11}
#Stability Tests for Monte Carlo methods

# We do this by checking the variance amongst the results when simulated many times.

CR = NULL
AN = NULL
MM = NULL
CV = NULL

# Determine the price under each method 100 times
for ( i in 1:100){
  CR[i]=Crude_Monte_Carlo()

}

for (i in 1:100){
  AN[i]=Antithetic_variates()

}

for (i in 1:100){
  MM[i]=Moment_Matching()
  
}

for (i in 1:100){
  CV[i]=Control_Variates_estimate()
}

VarCR=var(CR) # variance of Crude Monte Carlo
VarAN=var(AN) # variance of Antithetic Variates
VarMM=var(MM) # variance of Moment Matching
varCV=var(CV) # variance of Control Variates

```

```{r 12}
# Convergence Tests for finite difference methods
# Varying time steps

time_vec <- seq(1,100,1) # Steps to use

closed <- NULL # vector to hold closed form prices
CN_conv <- NULL # vector to hold Crank-Nicolson prices
Impl_conv <- NULL # vector to hold Implicit method prices
Expl_conv <- NULL # vector to hold Explicit method prices

for (i in 1:length(time_vec)){
  closed[i] <- bond_price()
}

for (i in 1:length(time_vec)){
  CN_conv[i] <- CN(I = 1:time_vec[i])
}

for (i in 1:length(time_vec)){
  Impl_conv[i] <- implicit(I = 1:time_vec[i])
}

for (i in 1:length(time_vec)){
  Expl_conv[i] <- explicit(I = 1:time_vec[i])
}

# Plot of convergence 
par(mfrow = c(1,1))
plot(closed, x = time_vec, type = "l", ylim = c(0.59,0.65), xlab = "Number of time steps", ylab = "Estimated Price" , lty =1, font.main = 1, main = "Finite Difference Bond Prices as Time Steps Increase")
lines(x = time_vec, y = CN_conv, type = "l", lty = 1, lwd =1.5, col = "green")
lines(x = time_vec, y = Impl_conv, type = "l", lty = 1, col = "blue",lwd =1.5)
lines(x = time_vec, y = Expl_conv, type = "l", lty = 1, col = "red",lwd =1.5)
legend(x = 60, y = 0.62, legend = c("Closed Form", "Crank-Nicolson", "Implicit", "Explicit"), lty = c(1,1,1,1), col = c("black","green","blue", "red"), cex = 0.8, bty ="n")

```




```{r 13}
# Covergence tests for Monte Carlo functions
# Varying time steps

trials_vec <- seq(10,10000,50) # Vector holding time steps

closed_1 <- NULL # vector to hold closed form prices
CR_conv <- NULL # vector to hold Crude Monte Carlo prices
AV_conv <- NULL # vector to hold Antithetic Variates prices
MM_conv <- NULL # vector to hold Moment Matching prices
CV_conv <- NULL # vector to hold Control Variates prices

for (i in 1:length(trials_vec)){
  closed_1[i] <- bond_price()
}

for (i in 1:length(trials_vec)){
  CR_conv[i] <- Crude_Monte_Carlo(n = trials_vec[i])
}

for (i in 1:length(trials_vec)){
  AV_conv[i] <- Antithetic_variates(n = trials_vec[i])
}

for (i in 1:length(trials_vec)){
  MM_conv[i] <- Moment_Matching(n = trials_vec[i])
}

for (i in 1:length(trials_vec)){
  CV_conv[i] <- Control_Variates_estimate(n = trials_vec[i])
}

# Plot of convergence
plot(closed_1, x = trials_vec, type = "l",ylim = c(0.617,0.624), xlab = "Number of Trials", ylab = "Estimated Price", lty = 2, lwd = 3,font.main = 1, main = "Monte Carlo Bond Prices over Number of Trials")
lines(x = trials_vec, y = CR_conv, type = "l", lty = 1, lwd =1.5)
lines(x = trials_vec, y = AV_conv, type = "l", lty = 1, col = "blue", lwd =4)
lines(x = trials_vec, y = MM_conv, type = "l", lty = 1, col = "green", lwd =3)
lines(x = trials_vec, y = CV_conv, type = "l", lty = 1, col = "red", lwd = 1.5)

legend(x = 600, y = 0.621, legend = c("Closed Form", "Crude Monte Carlo", "Antithetic Variates"), lty = c(2,1,1), lwd =c(1.5,1.5,1.5),col = c("black","black","blue"), cex = 0.9, bty="n")

legend(x = 5000, y = 0.621, legend = c("Moment Matching","Control Variates"), lty = c(1,1), lwd =c(1.5,1.5),col = c("green","red"), cex = 0.9, bty="n")

```



